listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix

wal_level = replica
max_wal_senders = 10

wal_keep_size = 128MB
max_wal_size = 1GB

archive_mode = on
archive_command = 'cp %p /var/lib/postgresql/data/archive/%f'
hot_standby = on