name: MovieApp.Nest.js
on: 
    push:
        branches: [master]
    pull_request:
        branches: [master]



jobs:
    basic:
        runs-on: ubuntu-latest
        services:
            postgres:
              image: postgres:14-alpine
              env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: moviedb
              options: >-
                   --health-cmd pg_isready
                   --health-interval 10s
                   --health-timeout 5s
                   --health-retries 5
              ports:
                - 5432:5432
            redis:
               image: redis:7.4 
               ports:
                - 6379:6379
               options: >-
                --health-cmd "redis-cli ping"
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
                
            maildev:
              image: maildev/maildev
              ports:
               - 1080:1080 
               - 1025:1025 
    

        steps:

            - name: Checkout
              uses: actions/checkout@v3  

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20.12.2
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: verify project structure
              run: |
                 echo "Checking project structure..."
                 ls -la src/auth/repositories/
                 cat tsconfig.json


            - name:  Wait for PostgreSQL to be ready
              run: |
                echo "Waiting for PostgreSQL to start..."
                for i in {1..10}; do
                  if pg_isready -h localhost -p 5432 -U postgres -d moviedb; then
                    echo "PostgreSQL is ready!"
                    break
                  else
                    echo "PostgreSQL is not ready yet. Retrying in 5 seconds..."
                    sleep 5
                  fi
                done

            - name: Set up env variables
              run:  |
                 echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
                 echo "NODE_ENV=test" >>  $GITHUB_ENV
                 echo "REDIS_HOST=localhost" >> $GITHUB_ENV
                 echo "REDIS_PORT=6379" >> $GITHUB_ENV
                 echo "REDIS_PASSWORD=testpass" >> $GITHUB_ENV
                 echo "JWT_ACCESS_SECRET=testjwtaccess" >> $GITHUB_ENV
                 echo "JWT_REFRESH_SECRET=testjwtaccess" >> $GITHUB_ENV
                 echo "SECRET_SESSION=testjwtacsesion" >> $GITHUB_ENV
                 echo "PAGINATION=5" >> $GITHUB_ENV
                 echo "SMTP_HOST=localhost" >> $GITHUB_ENV
                 echo "SMTP_PORT=1025" >> $GITHUB_ENV
          

        
            - name: Install prisma packages 
              env:
                DATABASE_URL: "postgres://postgres:postgres@localhost:5432/moviedb"
              run: |
                   npm install @prisma/client@6.4.0 
                   npm install prisma --save-dev
                   npx prisma generate
                   npx prisma migrate dev --name init

            - name: Build Typescript
              run: npm run build  
            
            - name: Lint
              run: npm run lint

            - name: Run Tests
              env: 
                DATABASE_URL: "postgres://postgres:postgres@localhost:5432/moviedb"
              run: npm run test:e2e

            - run:  echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
              
            